language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arghageek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arghageek/react-test npm run test

after_success:
  - docker build -t arghageek/multi-client ./client
  - docker build -t arghageek/multi-nginx ./nginx
  - docker build -t arghageek/multi-server ./server
  - docker build -t arghageek/multi-worker ./worker
