language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arghageek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arghageek/react-test npm run test

after_success:
  - docker build -t arghageek/multi-client ./client
  - docker build -t arghageek/multi-nginx ./nginx
  - docker build -t arghageek/multi-server ./server
  - docker build -t arghageek/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arghageek/multi-client
  - docker push arghageek/multi-nginx
  - docker push arghageek/multi-server
  - docker push arghageek/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-132416110445
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
